/* Supabase SQL schema */

-- Table: sensor_data
CREATE TABLE public.sensor_data (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_id TEXT NOT NULL,
  recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  water_percent NUMERIC,
  water_cm NUMERIC,
  water_status TEXT,
  light_lux NUMERIC,
  weather TEXT
);

-- Table: device_status
CREATE TABLE public.device_status (
  device_id TEXT PRIMARY KEY,
  last_seen TIMESTAMPTZ NOT NULL DEFAULT now(),
  is_online BOOLEAN NOT NULL,
  battery_v NUMERIC
);

-- Enable Row Level Security (optional, you can configure policies later)
ALTER TABLE public.sensor_data ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.device_status ENABLE ROW LEVEL SECURITY;
